### ISSUE TITLE
Option to disable URL encoding in cookie

### ISSUE THREAD

**Issue by ayya1987** [BCJTI/ng2-cookies#47]
Please give me a suggestion how to stop url encoding in cooking when i used to store as key value pair.

for ex; i am setting key as 'somepath' and value as '/path/path2/path3' after when i am looking inside browser it is different from actual value it is like  %2Fpath%2F% something like this.

Please help me to resolve this.

**Comment by Bigous** [comment]
Use the UnmanagedCookie (or UnmanagedCookieService) instead of Cookie (or CookieService). It was created to cases like this. It does no treatment on your cookies (neither on key nor on value) and you should care about doing things that can break browser behavior (like putting semi-colon on cookies).

You can use it just like you use the Cookie.
