### ISSUE TITLE
Cannot resolve 'file' or 'directoty'

### ISSUE THREAD

**Issue by Drabc** [BCJTI/ng2-cookies#5]
I'm working from this seed https://github.com/AngularClass/angular2-webpack-starter, and I keep getting these warnings. Is there something I'm missing?

I notice the npm install brings .d.ts files and does not include the .ts files. I'm new to webpack, so I'm not sure If I'm missing something.

It works perfectly if I install from github.

```
WARNING in ./~/ng2-cookies/ng2-cookies.js
Cannot find source file 'ng2-cookies.ts': Error: Cannot resolve 'file' or 'directory' ./ng2-cookies.ts in /home/dev/code/app/node_modules/ng2-cookies

WARNING in ./~/ng2-cookies/src/services.js
Cannot find source file 'services.ts': Error: Cannot resolve 'file' or 'directory' ./services.ts in /home/dev/code/app/node_modules/ng2-cookies/src

WARNING in ./~/ng2-cookies/src/services/cookie.js
Cannot find source file 'cookie.ts': Error: Cannot resolve 'file' or 'directory' ./cookie.ts in /home/dev/code/app/node_modules/ng2-cookies/src/services
```

**Comment by Bigous** [comment]
This is because of [this line](https://github.com/BCJTI/ng2-cookies/blob/master/.npmignore#L9).
Webpack should not warn you, because you have the .js file and the .d.ts file. It works as expected. I'ts just webpack warning that is annoying.
@carcamano if you want, you can just remove or put an ! or a # at the beginning of the line, or just close the issue because it's not a problem.
I don't have an opinion about it, but, for now, I have changed the [.npmignore from ng2-highcharts](https://github.com/Bigous/ng2-highcharts/blob/master/.npmignore#L9) so people using webpack don't receive the warning message.

**Comment by sasidhar** [comment]
As mentioned by @Bigous similar issue is discussed for https://github.com/Bigous/ng2-highcharts  here : https://github.com/Bigous/ng2-highcharts/issues/12

**Comment by carcamano** [comment]
Thank you @sasidhar 

NPM package updated and published!

**Comment by Drabc** [comment]
Thanks guys!
